<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Eason-PC" name="test.HelloworldWebdriverTestNG_Fail" tests="1" failures="0" timestamp="16 Apr 2015 07:44:50 GMT" time="30.512" errors="1">
  <testcase name="testOne_Fail" time="30.512" classname="test.HelloworldWebdriverTestNG_Fail">
    <error type="java.lang.AssertionError" message="expected [Selenium 中文论坛, Webdriver 中文论坛, Selenium2, 软件测试,web自动化测试_Fail] but found [selenium,webdriver,Selenium 中文论坛,Webdriver 中文论坛,Selenium2,软件测试,web自动化测试 - Powered by phpwind]">
      <![CDATA[java.lang.AssertionError: expected [Selenium 中文论坛, Webdriver 中文论坛, Selenium2, 软件测试,web自动化测试_Fail] but found [selenium,webdriver,Selenium 中文论坛,Webdriver 中文论坛,Selenium2,软件测试,web自动化测试 - Powered by phpwind]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test.HelloworldWebdriverTestNG_Fail.testOne_Fail(HelloworldWebdriverTestNG_Fail.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- testOne_Fail -->
</testsuite> <!-- test.HelloworldWebdriverTestNG_Fail -->
